from __future__ import annotations

from pathlib import Path
from typing import Optional

import pandas as pd


def _import_pyfolio():
    try:
        import pyfolio as pf  # provided by pyfolio-reloaded

        return pf
    except Exception as e:
        raise ImportError(
            "PyFolio is not installed. Install it with: pip install pyfolio-reloaded"
        ) from e


def pyfolio_generate(
    returns: pd.Series,
    benchmark_rets: Optional[pd.Series] = None,
    output_html: str | Path = "output/pyfolio_report.html",
    title: str = "PyFolio Tear Sheet",
    tag: str = "run",
    target: str = "strategy",
) -> Path:
    """
    Generate PyFolio full tear sheet (plots + tables) and export to HTML + PNGs
    This reproduces the "comprehensive tear sheet" feel, but in a CLI-friendly way by capturing Matplotlib figures and embedding them into HTML
    """

    import matplotlib.pyplot as plt

    import pandas as pd

    returns = returns.dropna()
    if benchmark_rets is not None:
        benchmark_rets = benchmark_rets.dropna()

    returns.index = pd.to_datetime(returns.index, utc=True)
    benchmark_rets.index = pd.to_datetime(benchmark_rets.index, utc=True)

    pf = _import_pyfolio()

    out_path = Path(output_html)

    if out_path.suffix.lower() != ".html":
        out_path.mkdir(parents=True, exist_ok=True)
        out_path = out_path / f"pyfolio_{target}_{tag}.html"

    out_dir = out_path.parent
    fig_dir = out_dir / f"{out_path.stem}_figures"
    fig_dir.mkdir(parents=True, exist_ok=True)

    plt.close("all")

    with pf.plotting.plotting_context(font_scale=1.1):
        pf.create_full_tear_sheet(
            returns=returns,
            benchmark_rets=benchmark_rets,
            set_context=False,
        )

    def _patch_legends(
        fig,
        strategy_label: str,
    ) -> None:
        # rename legend text after PyFolio generates figures
        for ax in fig.axes:
            leg = ax.get_legend()
            if not leg:
                continue
            for text in leg.get_texts():
                if text.get_text() == "Backtest":
                    text.set_text(strategy_label)

    # capture all figures created by PyFolio
    fig_nums = plt.get_fignums()
    fig_paths: list[Path] = []

    for i, num in enumerate(fig_nums, start=1):
        fig = plt.figure(num)
        _patch_legends(fig, strategy_label=target)
        path = fig_dir / f"pyfolio_{i:02d}.png"
        fig.savefig(path, dpi=160, bbox_inches="tight")
        fig_paths.append(path)

    perf_stats = pf.timeseries.perf_stats(returns, factor_returns=None)
    dd_table = pf.timeseries.gen_drawdown_table(returns, top=10)

    # builds HTML embedding PNGs
    imgs_html = "\n".join(f"""
        <div style="margin: 20px auto; max-width: 900px;">
            <img src="{fig_dir.name}/{p.name}"
                style="width: 100%; height: auto; display: block;">
        </div>
        """ for p in fig_paths)

    html = f"""<!doctype html>
    <html>
    <head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ margin-bottom: 10px; }}
        .meta {{ color: #555; margin-bottom: 20px; }}
        table {{ border-collapse: collapse; margin: 10px 0 30px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 6px 10px; }}
        th {{ background: #f6f6f6; }}
    </style>
    </head>
    <body>
    <h1>{title}</h1>
    <div class="meta">
        Generated by pyfolio-reloaded (CLI export)<br>
    </div>

    <h2>Performance Stats</h2>
    {perf_stats.to_frame("value").to_html()}

    <h2>Top Drawdowns</h2>
    {dd_table.to_html(index=False)}

    <h2>Plots</h2>
    {imgs_html}

    </body>
    </html>
    """
    out_path.write_text(html, encoding="utf-8")

    plt.close("all")
    return out_path
